// Tests for tools/dep-governance/discover-deps.mjs (#192).
//
// Run with: node --test tools/dep-governance/tests/discover.test.mjs
//
// Hermetic: uses fixtures/Cargo.lock.sample, fixtures/package-lock.json.sample,
// and an inline cargo metadata fragment. Does NOT touch the real repo's
// Cargo.lock or run `cargo metadata`.

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  parseCargoLockForChecksums,
  parseNpmLockfile,
  computeCargoScopes,
  buildCargoRecords,
  atomicWrite,
  renderInventoryText,
} from "../discover-deps.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.resolve(__dirname, "..", "fixtures");

// ---------------------------------------------------------------------------
// parseCargoLockForChecksums
// ---------------------------------------------------------------------------

test("parseCargoLockForChecksums: extracts name@version -> checksum", () => {
  const map = parseCargoLockForChecksums(path.join(FIXTURES, "Cargo.lock.sample"));
  assert.equal(map.get("adler2@2.0.1"), "320119579fcad9c21884f5c4861d16174d0e06250625266f50fe6898340abefa");
  assert.equal(map.get("tokio@1.52.3"), "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301");
  // Workspace members have no checksum (no `source` line, no `checksum`).
  assert.equal(map.get("airp-core@0.1.0"), null);
  // Packages with source but no checksum (rare) -> null.
  assert.equal(map.get("no-checksum-pkg@0.1.0"), null);
});

test("parseCargoLockForChecksums: missing file throws", () => {
  assert.throws(() => parseCargoLockForChecksums("/nonexistent/Cargo.lock"));
});

test("parseCargoLockForChecksums: non-package blocks do not pollute previous package", () => {
  // Cargo.lock v4 may contain [[patch.unused]], [[patch.<source>]], [[replace]],
  // [meta] or [metadata] blocks. These can carry `name = `, `version = `,
  // `checksum = ` lines that must NOT overwrite the previous [[package]]'s
  // fields. The parser must flush + null `cur` when entering any non-package
  // block.
  const tmp = path.join(FIXTURES, "..", "tmp-cargo-patch-blocks.test.lock");
  const cargoLockText = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "adler2"
version = "2.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "320119579fcad9c21884f5c4861d16174d0e06250625266f50fe6898340abefa"

[[patch.unused]]
name = "openssl-sys"
version = "0.9.100"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

[[package]]
name = "tokio"
version = "1.52.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301"

[meta]
target-applies-to-host = true
`;
  fs.writeFileSync(tmp, cargoLockText);
  try {
    const map = parseCargoLockForChecksums(tmp);
    // adler2 and tokio must have their correct checksums.
    assert.equal(
      map.get("adler2@2.0.1"),
      "320119579fcad9c21884f5c4861d16174d0e06250625266f50fe6898340abefa",
    );
    assert.equal(
      map.get("tokio@1.52.3"),
      "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301",
    );
    // The [[patch.unused]] entry for openssl-sys must NOT be recorded as a
    // package checksum (it's a patch declaration, not an installed package).
    assert.equal(map.get("openssl-sys@0.9.100"), undefined);
    // The [meta] block has no name/version/checksum, but we make sure it
    // doesn't crash the parser or pollute any previous entry.
    assert.equal(map.size, 2);
  } finally {
    fs.unlinkSync(tmp);
  }
});

// ---------------------------------------------------------------------------
// parseNpmLockfile
// ---------------------------------------------------------------------------

test("parseNpmLockfile: parses v3 packages, marks root as first-party", () => {
  const records = parseNpmLockfile(
    path.join(FIXTURES, "package-lock.json.sample"),
    "airp-ui",
  );
  // Root + 3 hoisted packages = 4 records. The nested bar (node_modules/foo/node_modules/bar)
  // is skipped because it's not hoisted to the top node_modules/ level.
  assert.equal(records.length, 4);

  const root = records.find((r) => r.name === "airp-ui");
  assert.equal(root.tier, "first-party");
  assert.equal(root.scope, "runtime");
  assert.equal(root.source, "workspace");
  assert.equal(root.license, "MIT OR Apache-2.0");

  const vue = records.find((r) => r.name === "vue");
  assert.equal(vue.version, "3.5.39");
  assert.equal(vue.license, "MIT");
  assert.equal(vue.scope, "runtime");
  assert.equal(vue.tier, "third-party");
  assert.equal(vue.source, "npm");
  assert.match(vue.resolved, /^https:\/\/registry\.npmjs\.org\/vue\//);
  assert.match(vue.integrity, /^sha512-/);

  // dev packages
  const ts = records.find((r) => r.name === "typescript");
  assert.equal(ts.scope, "dev");
  const vite = records.find((r) => r.name === "vite");
  assert.equal(vite.scope, "dev");

  // Nested bar is skipped (we keep only hoisted entries).
  const bar = records.find((r) => r.name === "bar");
  assert.equal(bar, undefined);
});

test("parseNpmLockfile: rejects unsupported lockfileVersion", () => {
  // Write a v1 lockfile to a tmp path and assert it throws.
  const tmp = path.join(FIXTURES, "..", "tmp-v1-lock.test.json");
  fs.writeFileSync(tmp, JSON.stringify({ lockfileVersion: 1, dependencies: {} }));
  try {
    assert.throws(() => parseNpmLockfile(tmp, "airp-ui"), /lockfileVersion 1/);
  } finally {
    fs.unlinkSync(tmp);
  }
});

test("parseNpmLockfile: workspace link (info.link=true) marked as first-party", () => {
  // npm workspaces create symlinked entries in node_modules/ with
  // `link: true` in package-lock.json v3. These are first-party workspace
  // members and must be classified as tier=first-party, source=workspace
  // (NOT third-party with source=link), so they carry AIRP's own license
  // rather than being audited as third-party.
  const tmp = path.join(FIXTURES, "..", "tmp-npm-workspace-link.test.json");
  const lockfile = {
    name: "airp-ui",
    version: "0.1.0",
    lockfileVersion: 3,
    requires: true,
    packages: {
      "": {
        name: "airp-ui",
        version: "0.1.0",
        license: "MIT OR Apache-2.0",
        dependencies: { "@airp/shared": "workspace:*" },
      },
      "node_modules/@airp/shared": {
        name: "@airp/shared",
        version: "0.1.0",
        license: "MIT OR Apache-2.0",
        resolved: "packages/shared", // workspace path (relative)
        link: true,
      },
      "node_modules/vue": {
        version: "3.5.39",
        license: "MIT",
        resolved: "https://registry.npmjs.org/vue/-/vue-3.5.39.tgz",
        integrity: "sha512-aaaa==",
      },
    },
  };
  fs.writeFileSync(tmp, JSON.stringify(lockfile));
  try {
    const records = parseNpmLockfile(tmp, "airp-ui");
    // Root + workspace link + vue = 3 records.
    assert.equal(records.length, 3);

    const shared = records.find((r) => r.name === "@airp/shared");
    assert.ok(shared, "workspace link record must exist");
    assert.equal(shared.tier, "first-party");
    assert.equal(shared.source, "workspace");
    assert.equal(shared.license, "MIT OR Apache-2.0");

    // Regular npm package stays third-party.
    const vue = records.find((r) => r.name === "vue");
    assert.equal(vue.tier, "third-party");
    assert.equal(vue.source, "npm");

    // Root is still first-party.
    const root = records.find((r) => r.name === "airp-ui");
    assert.equal(root.tier, "first-party");
  } finally {
    fs.unlinkSync(tmp);
  }
});

test("parseNpmLockfile: git dep (resolved starts with git+) stays third-party", () => {
  // A git+resolved package is NOT a workspace link even if it somehow had
  // link=true (it shouldn't, but we guard). Git deps must remain
  // third-party with source=git so they get audited.
  const tmp = path.join(FIXTURES, "..", "tmp-npm-git-dep.test.json");
  const lockfile = {
    name: "airp-ui",
    version: "0.1.0",
    lockfileVersion: 3,
    requires: true,
    packages: {
      "": { name: "airp-ui", version: "0.1.0", license: "MIT OR Apache-2.0" },
      "node_modules/forked-lib": {
        version: "1.0.0",
        license: "MIT",
        resolved: "git+https://github.com/forked/lib.git#abcdef123456",
        integrity: "sha512-bbbb==",
      },
    },
  };
  fs.writeFileSync(tmp, JSON.stringify(lockfile));
  try {
    const records = parseNpmLockfile(tmp, "airp-ui");
    const forked = records.find((r) => r.name === "forked-lib");
    assert.equal(forked.tier, "third-party");
    assert.equal(forked.source, "git");
  } finally {
    fs.unlinkSync(tmp);
  }
});

// ---------------------------------------------------------------------------
// computeCargoScopes + buildCargoRecords (with inline metadata fixture)
// ---------------------------------------------------------------------------

// Minimal cargo metadata fragment exercising scope classification.
// Graph:
//   airp-core (workspace member)
//     normal dep: tokio            -> runtime
//     normal dep: serde            -> runtime
//     build dep:  tauri-build      -> build
//     dev dep:    wiremock         -> dev
//   tokio
//     normal dep: bytes            -> runtime (transitive, via normal edge)
//   wiremock
//     normal dep: tokio            -> runtime (but wiremock is dev-scoped, so
//                                          tokio's dev-path doesn't downgrade it)
const METADATA_FIXTURE = {
  workspace_members: ["airp-core 0.1.0 (path+file:///workspace/engine)"],
  packages: [
    {
      id: "airp-core 0.1.0 (path+file:///workspace/engine)",
      name: "airp-core",
      version: "0.1.0",
      license: "MIT OR Apache-2.0",
      repository: "https://github.com/GhostXia/AIRP",
      source: null,
      manifest_path: "/workspace/engine/Cargo.toml",
      homepage: null,
      description: "AIRP-Core",
    },
    {
      id: "tokio 1.52.3 (registry+https://github.com/rust-lang/crates.io-index)",
      name: "tokio",
      version: "1.52.3",
      license: "MIT",
      repository: "https://github.com/tokio-rs/tokio",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest_path: null,
      homepage: "https://tokio.rs",
      description: "Event-driven I/O",
    },
    {
      id: "serde 1.0.210 (registry+https://github.com/rust-lang/crates.io-index)",
      name: "serde",
      version: "1.0.210",
      license: "MIT OR Apache-2.0",
      repository: "https://github.com/serde-rs/serde",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest_path: null,
      homepage: null,
      description: "serialization",
    },
    {
      id: "tauri-build 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
      name: "tauri-build",
      version: "2.0.0",
      license: "MIT OR Apache-2.0",
      repository: "https://github.com/tauri-apps/tauri",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest_path: null,
      homepage: null,
      description: "build script",
    },
    {
      id: "wiremock 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)",
      name: "wiremock",
      version: "0.6.0",
      license: "MIT",
      repository: "https://github.com/seanmonstar/wiremock",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest_path: null,
      homepage: null,
      description: "mock server",
    },
    {
      id: "bytes 1.7.0 (registry+https://github.com/rust-lang/crates.io-index)",
      name: "bytes",
      version: "1.7.0",
      license: "MIT",
      repository: "https://github.com/tokio-rs/bytes",
      source: "registry+https://github.com/rust-lang/crates.io-index",
      manifest_path: null,
      homepage: null,
      description: "byte buffer",
    },
  ],
  resolve: {
    nodes: [
      {
        id: "airp-core 0.1.0 (path+file:///workspace/engine)",
        deps: [
          { pkg: "tokio 1.52.3 (registry+https://github.com/rust-lang/crates.io-index)", dep_kinds: [{ kind: null }] },
          { pkg: "serde 1.0.210 (registry+https://github.com/rust-lang/crates.io-index)", dep_kinds: [{ kind: null }] },
          { pkg: "tauri-build 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)", dep_kinds: [{ kind: "build" }] },
          { pkg: "wiremock 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)", dep_kinds: [{ kind: "dev" }] },
        ],
      },
      {
        id: "tokio 1.52.3 (registry+https://github.com/rust-lang/crates.io-index)",
        deps: [
          { pkg: "bytes 1.7.0 (registry+https://github.com/rust-lang/crates.io-index)", dep_kinds: [{ kind: null }] },
        ],
      },
      {
        id: "wiremock 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)",
        deps: [
          { pkg: "tokio 1.52.3 (registry+https://github.com/rust-lang/crates.io-index)", dep_kinds: [{ kind: null }] },
        ],
      },
    ],
  },
};

test("computeCargoScopes: classifies workspace member and edges", () => {
  const scopes = computeCargoScopes(METADATA_FIXTURE);
  // Workspace member itself.
  assert.equal(scopes.get("airp-core 0.1.0 (path+file:///workspace/engine)"), "runtime");
  // Normal dep -> runtime.
  assert.equal(scopes.get("tokio 1.52.3 (registry+https://github.com/rust-lang/crates.io-index)"), "runtime");
  assert.equal(scopes.get("serde 1.0.210 (registry+https://github.com/rust-lang/crates.io-index)"), "runtime");
  // Build dep -> build.
  assert.equal(scopes.get("tauri-build 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)"), "build");
  // Dev dep -> dev.
  assert.equal(scopes.get("wiremock 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)"), "dev");
  // Transitive normal dep of runtime dep -> runtime.
  assert.equal(scopes.get("bytes 1.7.0 (registry+https://github.com/rust-lang/crates.io-index)"), "runtime");
});

test("buildCargoRecords: marks tiers and sources correctly", () => {
  const checksums = new Map([
    ["tokio@1.52.3", "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301"],
    ["bytes@1.7.0", null],
  ]);
  const records = buildCargoRecords(METADATA_FIXTURE, checksums, ["airp-core", "airp-state-protocol", "airp-ui"]);

  const airp = records.find((r) => r.name === "airp-core");
  assert.equal(airp.tier, "first-party");
  assert.equal(airp.source, "workspace");
  assert.equal(airp.resolved, null);

  const tokio = records.find((r) => r.name === "tokio");
  assert.equal(tokio.tier, "third-party");
  assert.equal(tokio.source, "crates.io");
  assert.equal(tokio.integrity, "sha256:ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301");
  assert.equal(tokio.scope, "runtime");
  assert.match(tokio.resolved, /^https:\/\/crates\.io\/api\/v1\/crates\/tokio\/1\.52\.3\/download$/);

  // bytes has no checksum in our fixture map -> integrity null.
  const bytes = records.find((r) => r.name === "bytes");
  assert.equal(bytes.integrity, null);
});

// ---------------------------------------------------------------------------
// atomicWrite
// ---------------------------------------------------------------------------

test("atomicWrite: writes file and cleans up tmp on success", async () => {
  const target = path.join(FIXTURES, "..", "tmp-atomic-write.test.txt");
  try {
    atomicWrite(target, "hello");
    assert.equal(fs.readFileSync(target, "utf8"), "hello");
    // tmp file must not linger.
    assert.equal(fs.existsSync(`${target}.tmp`), false);
  } finally {
    try { fs.unlinkSync(target); } catch {}
  }
});

test("atomicWrite: does not leave partial file if rename target is invalid", () => {
  // Renaming into a non-existent directory throws. The tmp file should be
  // cleaned up and no final file created.
  const badTarget = path.join(FIXTURES, "..", "nonexistent-dir", "tmp-atomic-fail.test.txt");
  assert.throws(() => atomicWrite(badTarget, "hello"));
  assert.equal(fs.existsSync(badTarget), false);
  // tmp in the (also non-existent) dir won't exist either.
  assert.equal(fs.existsSync(`${badTarget}.tmp`), false);
});

// ---------------------------------------------------------------------------
// renderInventoryText
// ---------------------------------------------------------------------------

test("renderInventoryText: includes attention section for block/audit-required", () => {
  const records = [
    { ecosystem: "cargo", name: "good", version: "1.0.0", audit_class: "auto-pass", audit_reason: "MIT", license_normalized: "MIT", scope: "runtime", tier: "third-party", resolved: null },
    { ecosystem: "cargo", name: "bad", version: "2.0.0", audit_class: "block", audit_reason: "GPL-3.0 in runtime", license_normalized: "GPL-3.0", scope: "runtime", tier: "third-party", resolved: "https://example.com" },
  ];
  const meta = {
    generated_at: "2026-07-18T00:00:00.000Z",
    repo_root: "/workspace",
    total_records: 2,
    summary: {
      by_audit_class: { "auto-pass": 1, block: 1 },
      by_ecosystem: { cargo: 2 },
    },
  };
  const text = renderInventoryText(records, meta);
  assert.match(text, /AIRP dependency inventory/);
  assert.match(text, /Records requiring attention/);
  assert.match(text, /\[block\] cargo\/bad@2\.0\.0/);
  assert.match(text, /GPL-3\.0 in runtime/);
});
