// OpenAI 兼容 LLM 客户端。与 engine provider 解耦：runner 自带 client。
// 环境变量：OPENAI_BASE_URL, OPENAI_API_KEY, OPENAI_MODEL（默认 gpt-4o-mini）
//
// B9 方案 3（fallback 模式）：当 OPENAI_API_KEY 未配时不再 process.exit(2)，
// 而是进入 fallback 模式 —— runner 调 getBuiltinSmokeScript() 拿到一个内置
// minimal smoke 脚本（只 navigate + snapshot，不做业务断言）。
//
// 这样 CI 可在零密钥情况下完整验证 topology + harness + runner + reporter +
// commenter 全链路可达；secret 已配时走真 LLM 路径（方案 1 的正常流）。
//
// 设计权衡：
//   - 不用 mock-provider.js：它返回 RP 文本，runner 的 extractCodeBlock() 期望
//     ```js 代码块，二者不兼容；而且 mock 已被 engine 用作 chat provider，
//     复用会让"runner 是否真调到 LLM"模糊。
//   - 不在 runner 里硬编码脚本：保持 llm-client 是 fallback 决策唯一来源，
//     runner 只通过 FALLBACK_MODE + getBuiltinSmokeScript() 消费。

const BASE_URL = process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1';
const API_KEY = process.env.OPENAI_API_KEY;
const MODEL = process.env.OPENAI_MODEL || 'gpt-4o-mini';

// B9 方案 3：fallback 标志对外暴露，runner 据此分支。
export const FALLBACK_MODE = !API_KEY;

if (FALLBACK_MODE) {
  console.warn([
    '[llm-client] OPENAI_API_KEY is not set; entering fallback mode.',
    '',
    'Fallback mode returns a built-in minimal smoke script (navigate + snapshot only).',
    'This validates topology + harness pipeline without calling a real LLM.',
    '',
    'To run real agent-generated scripts, configure the key:',
    '  Local: $env:OPENAI_API_KEY = "sk-..."  (PowerShell)',
    '         export OPENAI_API_KEY="sk-..."   (bash)',
    '  CI:    Add repo secret AGENT_EXPLORATION_OPENAI_KEY = sk-...',
    '         at: https://github.com/<owner>/<repo>/settings/secrets/actions',
    '',
    'Workflow is continue-on-error: true; merge is not blocked.',
  ].join('\n'));
}

// B9 方案 3：内置 minimal smoke 脚本。
// 设计目标：验证 topology + harness + runner + reporter + commenter 全链路可达，
// 不做任何业务断言（fallback 模式不是"测试"，是"管线自检"）。
// 脚本只 navigate 到 4 个关键 screen + 调 harness.getDomSnapshot() 留快照。
// 失败意味着 topology/harness 自身有问题（不是 WebUI 业务 bug）。
const BUILTIN_SMOKE_SCRIPT = `// B9 fallback: built-in minimal smoke script (no real LLM).
// Generated by llm-client.mjs when OPENAI_API_KEY is missing.
// Purpose: validate topology + harness pipeline end-to-end without calling an LLM.
// No business assertions — failure here means topology/harness is broken,
// NOT that the WebUI has a bug.

export async function run(ctx) {
  const screens = [
    '01-role-list.html',
    '16-onboarding.html',
    '17-memory-state.html',
    '19-branch-tree.html',
  ];
  for (const s of screens) {
    await ctx.harness.navigate(s);
    // 等 harness 在新 screen 上重新安装（screen reload 后 __AIRP_AGENT_TEST__ 重新挂载）
    await ctx.harness.waitFor('no-pending-request', 3000).catch(() => false);
    const snap = ctx.harness.getDomSnapshot();
    if (!Array.isArray(snap) || snap.length === 0) {
      throw new Error('ASSERT: harness returned empty DOM snapshot at ' + s);
    }
  }
}
`;

export function getBuiltinSmokeScript() {
  return BUILTIN_SMOKE_SCRIPT;
}

export async function chatCompletion(messages, { maxTokens = 2048, temperature = 0.2, timeoutMs = 60000 } = {}) {
  if (FALLBACK_MODE) {
    // 防御性：runner 不应在 fallback 模式下调本函数。若误调，抛错让上层修复，
    // 而不是静默返回空字符串让 runner 后续 extractCodeBlock 拿到 undefined。
    throw new Error('chatCompletion called in fallback mode (no OPENAI_API_KEY); runner should use getBuiltinSmokeScript() instead');
  }
  // Bounded deadline: 防止 stalled provider 把 task/workflow 拖到 30 分钟超时
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  let res;
  try {
    res = await fetch(BASE_URL + '/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + API_KEY,
      },
      body: JSON.stringify({ model: MODEL, messages, max_tokens: maxTokens, temperature }),
      signal: controller.signal,
    });
  } catch (err) {
    if (err && err.name === 'AbortError') {
      throw new Error('LLM request timed out after ' + timeoutMs + 'ms (provider stalled?)');
    }
    throw err;
  } finally {
    clearTimeout(timer);
  }
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`LLM ${res.status}: ${text}`);
  }
  const json = await res.json();
  return json.choices?.[0]?.message?.content || '';
}

export function getModel() {
  // fallback 模式下让 reporter 自然展示 fallback 标识，让 PR 评论读者一眼能区分
  // "本报告是管线自检，不是真 Agent 探索"。
  return FALLBACK_MODE ? MODEL + ' (fallback: built-in smoke script)' : MODEL;
}
